spring:
  config:
    import:
      - classpath:/final-secret/application-dev.yml
      - classpath:/final-secret/application-local.yml
      - classpath:/final-secret/application-test.yml

  profiles:
    default: dev
    active: dev

springdoc:
  use-fqn: true
  api-docs:
    version: openapi_3_0
    path: /public-api/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /public-api/swagger-ui
    disable-swagger-default-url: true
    display-request-duration: true
  paths-to-match:
    - /**

discord:
  webhook:
    url: