ALTER TABLE contracts DROP FOREIGN KEY FK_CONTRACTS_ON_ROOM;
ALTER TABLE contracts DROP FOREIGN KEY FK_CONTRACTS_ON_TENANT;

ALTER TABLE contracts DROP INDEX uc_contracts_room;
ALTER TABLE contracts DROP INDEX uc_contracts_tenant;

ALTER TABLE contracts ADD CONSTRAINT FK_CONTRACTS_ON_ROOM FOREIGN KEY (room_id) REFERENCES rooms (id);
ALTER TABLE contracts ADD CONSTRAINT FK_CONTRACTS_ON_TENANT FOREIGN KEY (tenant_id) REFERENCES tenants (id);