name: Backend Server Deploy to AWS EC2 and Docker

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build and Test with Gradle
        run: ./gradlew clean build --parallel -x test
        shell: bash

      - name: Docker Build & Push to Hub
        run: |
          docker login -u woohahalife -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker build -t woohahalife/back9-backend -f ./.docker/Dockerfile .
          docker push woohahalife/back9-backend

      - name: Send docker-compose.yml to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "./.docker/docker-compose.yml"
          target: "/home/ubuntu"

      - name: Send deploy.sh to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "./scripts"
          target: "/home/ubuntu"

      - name: Deploy to Develop
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            sudo cp /home/ubuntu/.docker/docker-compose.yml /home/ubuntu
            sudo cp /home/ubuntu/scripts/deploy.sh /home/ubuntu
            docker pull woohahalife/back9-backend
            sudo chmod 777 ./deploy.sh
            ./deploy.sh
            docker image prune -f
